# Dockerfile.dev
FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000
# Run the dev script. We rely on docker-compose env var `NEXT_PRIVATE_NO_TURBOPACK`
# (set in docker-compose.dev.yml) to disable Turbopack when desired.
CMD ["npm", "run", "dev"]
