services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: back_premaut
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    env_file:
      - .env
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
  
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm test
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: front_premaut
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_PRIVATE_NO_TURBOPACK: "1"
      NEXT_TELEMETRY_DISABLED: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536